### ISSUE TITLE
Incompatibility on NixOS

### ISSUE THREAD

**Issue by M-Gregoire** [kee-org/keepassrpc#61]
***Info***
Using KeePass 2.40 and Keepassrpc 1.8.0

***Summary***
Starting Keepass with the keepassrpc plugins gives me the following error:
"The following plugin is incompatible with the current KeePass version: /path/to/KeePassRPC.plgx Have a look at the plugin's website for an appropriate version."

I believe that this issue is different than #53 because the debug message below is different. Also, please note I'm using NixOS but I'm unsure this is the problem.

***Debug***

`keepass --debug` output the following to a temporary file, after showing a popup `Compilation failed. Compiler results saved to ...`
```
Compiler 'null':

/nix/store/1k1n5j167cz1rqjnyhi63jg52bigxnj1-mono-5.4.1.6/bin/mcs /target:library /debug- /optimize+ /out:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.dll" /r:"System.dll" /r:"System.Configuration.dll" /r:"System.Configuration.Install.dll" /r:"System.Data.dll" /r:"System.Drawing.dll" /r:"System.Management.dll" /r:"System.Security.dll" /r:"System.Windows.Forms.dll" /r:"System.Xml.dll" /r:"/nix/store/mfvx22qhxlzm94jmrlm174cr1ii18riq-keepass-2.40/lib/dotnet/keepass/KeePass.exe" /r:"/home/user/.local/share/KeePass/PluginCache/m55ZrTiK9evjCyNUgeCg/DomainPublicSuffix.dll" /r:"/home/user/.local/share/KeePass/PluginCache/m55ZrTiK9evjCyNUgeCg/Fleck2.dll" /r:"/home/user/.local/share/KeePass/PluginCache/m55ZrTiK9evjCyNUgeCg/Jayrock.dll" /r:"/home/user/.local/share/KeePass/PluginCache/m55ZrTiK9evjCyNUgeCg/Jayrock.Json.dll" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.AuthForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.KeeFoxEntryUserControl.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.KeeFoxFieldForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.KeeFoxGroupUserControl.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.KeeFoxURLForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.KeyCreationSimpleForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.LocationManager.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.OptionsForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.WelcomeForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Properties.Resources.resources" /noconfig  -- "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/BigInteger.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/DataExchangeModel.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/DpiFix.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Extensions.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/AuthForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/AuthForm.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxEntryUserControl.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxEntryUserControl.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxFieldForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxFieldForm.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxGroupUserControl.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxGroupUserControl.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxURLForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxURLForm.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeyCreationSimpleForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeyCreationSimpleForm.designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/LocationManager.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/LocationManager.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/WelcomeForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/WelcomeForm.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPCClient.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPCExt.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPCServer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPCService.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/OptionsForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/OptionsForm.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeyChallengeResponse.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeyContainerClass.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Native.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Properties/AssemblyInfo.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Properties/Resources.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/RPCClientManagers.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/SRP.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/URLSummary.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Utils.cs"
/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Extensions.cs(7,14): error CS0234: The type or namespace name `Linq' does not exist in the namespace `System'. Are you missing `System.Core' assembly reference?
/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPCClient.cs(11,14): error CS0234: The type or namespace name `Linq' does not exist in the namespace `System'. Are you missing `System.Core' assembly reference?
/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/DataExchangeModel.cs(247,18): warning CS0659: `KeePassRPC.DataExchangeModel.EntryConfig' overrides Object.Equals(object) but does not override Object.GetHashCode()
/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeyCreationSimpleForm.cs(42,11): error CS0246: The type or namespace name `SecureEdit' could not be found. Are you missing an assembly reference?
/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeyCreationSimpleForm.cs(43,11): error CS0246: The type or namespace name `SecureEdit' could not be found. Are you missing an assembly reference?



==============================================================================
Compiler 'v4':

/nix/store/1k1n5j167cz1rqjnyhi63jg52bigxnj1-mono-5.4.1.6/bin/mcs /target:library /debug- /optimize+ /out:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.dll" /r:"System.dll" /r:"System.Configuration.dll" /r:"System.Configuration.Install.dll" /r:"System.Data.dll" /r:"System.Drawing.dll" /r:"System.Management.dll" /r:"System.Security.dll" /r:"System.Windows.Forms.dll" /r:"System.Xml.dll" /r:"/nix/store/mfvx22qhxlzm94jmrlm174cr1ii18riq-keepass-2.40/lib/dotnet/keepass/KeePass.exe" /r:"/home/user/.local/share/KeePass/PluginCache/m55ZrTiK9evjCyNUgeCg/DomainPublicSuffix.dll" /r:"/home/user/.local/share/KeePass/PluginCache/m55ZrTiK9evjCyNUgeCg/Fleck2.dll" /r:"/home/user/.local/share/KeePass/PluginCache/m55ZrTiK9evjCyNUgeCg/Jayrock.dll" /r:"/home/user/.local/share/KeePass/PluginCache/m55ZrTiK9evjCyNUgeCg/Jayrock.Json.dll" /r:"System.Core.dll" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.AuthForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.KeeFoxEntryUserControl.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.KeeFoxFieldForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.KeeFoxGroupUserControl.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.KeeFoxURLForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.KeyCreationSimpleForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.LocationManager.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.OptionsForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.WelcomeForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Properties.Resources.resources" /noconfig  -- "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/BigInteger.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/DataExchangeModel.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/DpiFix.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Extensions.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/AuthForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/AuthForm.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxEntryUserControl.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxEntryUserControl.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxFieldForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxFieldForm.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxGroupUserControl.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxGroupUserControl.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxURLForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxURLForm.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeyCreationSimpleForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeyCreationSimpleForm.designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/LocationManager.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/LocationManager.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/WelcomeForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/WelcomeForm.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPCClient.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPCExt.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPCServer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPCService.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/OptionsForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/OptionsForm.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeyChallengeResponse.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeyContainerClass.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Native.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Properties/AssemblyInfo.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Properties/Resources.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/RPCClientManagers.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/SRP.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/URLSummary.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Utils.cs"
/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/DataExchangeModel.cs(247,18): warning CS0659: `KeePassRPC.DataExchangeModel.EntryConfig' overrides Object.Equals(object) but does not override Object.GetHashCode()
/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeyCreationSimpleForm.cs(42,11): error CS0246: The type or namespace name `SecureEdit' could not be found. Are you missing an assembly reference?
/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeyCreationSimpleForm.cs(43,11): error CS0246: The type or namespace name `SecureEdit' could not be found. Are you missing an assembly reference?



==============================================================================
Compiler 'v4.0':

/nix/store/1k1n5j167cz1rqjnyhi63jg52bigxnj1-mono-5.4.1.6/bin/mcs /target:library /debug- /optimize+ /out:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.dll" /r:"System.dll" /r:"System.Configuration.dll" /r:"System.Configuration.Install.dll" /r:"System.Data.dll" /r:"System.Drawing.dll" /r:"System.Management.dll" /r:"System.Security.dll" /r:"System.Windows.Forms.dll" /r:"System.Xml.dll" /r:"/nix/store/mfvx22qhxlzm94jmrlm174cr1ii18riq-keepass-2.40/lib/dotnet/keepass/KeePass.exe" /r:"/home/user/.local/share/KeePass/PluginCache/m55ZrTiK9evjCyNUgeCg/DomainPublicSuffix.dll" /r:"/home/user/.local/share/KeePass/PluginCache/m55ZrTiK9evjCyNUgeCg/Fleck2.dll" /r:"/home/user/.local/share/KeePass/PluginCache/m55ZrTiK9evjCyNUgeCg/Jayrock.dll" /r:"/home/user/.local/share/KeePass/PluginCache/m55ZrTiK9evjCyNUgeCg/Jayrock.Json.dll" /r:"System.Core.dll" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.AuthForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.KeeFoxEntryUserControl.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.KeeFoxFieldForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.KeeFoxGroupUserControl.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.KeeFoxURLForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.KeyCreationSimpleForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.LocationManager.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.OptionsForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.WelcomeForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Properties.Resources.resources" /noconfig  -- "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/BigInteger.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/DataExchangeModel.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/DpiFix.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Extensions.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/AuthForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/AuthForm.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxEntryUserControl.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxEntryUserControl.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxFieldForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxFieldForm.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxGroupUserControl.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxGroupUserControl.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxURLForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxURLForm.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeyCreationSimpleForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeyCreationSimpleForm.designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/LocationManager.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/LocationManager.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/WelcomeForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/WelcomeForm.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPCClient.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPCExt.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPCServer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPCService.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/OptionsForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/OptionsForm.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeyChallengeResponse.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeyContainerClass.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Native.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Properties/AssemblyInfo.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Properties/Resources.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/RPCClientManagers.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/SRP.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/URLSummary.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Utils.cs"
/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/DataExchangeModel.cs(247,18): warning CS0659: `KeePassRPC.DataExchangeModel.EntryConfig' overrides Object.Equals(object) but does not override Object.GetHashCode()
/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeyCreationSimpleForm.cs(42,11): error CS0246: The type or namespace name `SecureEdit' could not be found. Are you missing an assembly reference?
/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeyCreationSimpleForm.cs(43,11): error CS0246: The type or namespace name `SecureEdit' could not be found. Are you missing an assembly reference?



==============================================================================
Compiler 'v4.0.30319':

/nix/store/1k1n5j167cz1rqjnyhi63jg52bigxnj1-mono-5.4.1.6/bin/mcs /target:library /debug- /optimize+ /out:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.dll" /r:"System.dll" /r:"System.Configuration.dll" /r:"System.Configuration.Install.dll" /r:"System.Data.dll" /r:"System.Drawing.dll" /r:"System.Management.dll" /r:"System.Security.dll" /r:"System.Windows.Forms.dll" /r:"System.Xml.dll" /r:"/nix/store/mfvx22qhxlzm94jmrlm174cr1ii18riq-keepass-2.40/lib/dotnet/keepass/KeePass.exe" /r:"/home/user/.local/share/KeePass/PluginCache/m55ZrTiK9evjCyNUgeCg/DomainPublicSuffix.dll" /r:"/home/user/.local/share/KeePass/PluginCache/m55ZrTiK9evjCyNUgeCg/Fleck2.dll" /r:"/home/user/.local/share/KeePass/PluginCache/m55ZrTiK9evjCyNUgeCg/Jayrock.dll" /r:"/home/user/.local/share/KeePass/PluginCache/m55ZrTiK9evjCyNUgeCg/Jayrock.Json.dll" /r:"System.Core.dll" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.AuthForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.KeeFoxEntryUserControl.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.KeeFoxFieldForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.KeeFoxGroupUserControl.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.KeeFoxURLForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.KeyCreationSimpleForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.LocationManager.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.OptionsForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.WelcomeForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Properties.Resources.resources" /noconfig  -- "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/BigInteger.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/DataExchangeModel.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/DpiFix.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Extensions.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/AuthForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/AuthForm.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxEntryUserControl.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxEntryUserControl.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxFieldForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxFieldForm.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxGroupUserControl.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxGroupUserControl.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxURLForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxURLForm.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeyCreationSimpleForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeyCreationSimpleForm.designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/LocationManager.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/LocationManager.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/WelcomeForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/WelcomeForm.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPCClient.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPCExt.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPCServer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPCService.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/OptionsForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/OptionsForm.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeyChallengeResponse.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeyContainerClass.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Native.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Properties/AssemblyInfo.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Properties/Resources.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/RPCClientManagers.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/SRP.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/URLSummary.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Utils.cs"
/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/DataExchangeModel.cs(247,18): warning CS0659: `KeePassRPC.DataExchangeModel.EntryConfig' overrides Object.Equals(object) but does not override Object.GetHashCode()
/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeyCreationSimpleForm.cs(42,11): error CS0246: The type or namespace name `SecureEdit' could not be found. Are you missing an assembly reference?
/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeyCreationSimpleForm.cs(43,11): error CS0246: The type or namespace name `SecureEdit' could not be found. Are you missing an assembly reference?



==============================================================================
Compiler 'v4.5':

/nix/store/1k1n5j167cz1rqjnyhi63jg52bigxnj1-mono-5.4.1.6/bin/mcs /target:library /debug- /optimize+ /out:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.dll" /r:"System.dll" /r:"System.Configuration.dll" /r:"System.Configuration.Install.dll" /r:"System.Data.dll" /r:"System.Drawing.dll" /r:"System.Management.dll" /r:"System.Security.dll" /r:"System.Windows.Forms.dll" /r:"System.Xml.dll" /r:"/nix/store/mfvx22qhxlzm94jmrlm174cr1ii18riq-keepass-2.40/lib/dotnet/keepass/KeePass.exe" /r:"/home/user/.local/share/KeePass/PluginCache/m55ZrTiK9evjCyNUgeCg/DomainPublicSuffix.dll" /r:"/home/user/.local/share/KeePass/PluginCache/m55ZrTiK9evjCyNUgeCg/Fleck2.dll" /r:"/home/user/.local/share/KeePass/PluginCache/m55ZrTiK9evjCyNUgeCg/Jayrock.dll" /r:"/home/user/.local/share/KeePass/PluginCache/m55ZrTiK9evjCyNUgeCg/Jayrock.Json.dll" /r:"System.Core.dll" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.AuthForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.KeeFoxEntryUserControl.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.KeeFoxFieldForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.KeeFoxGroupUserControl.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.KeeFoxURLForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.KeyCreationSimpleForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.LocationManager.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.OptionsForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.WelcomeForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Properties.Resources.resources" /noconfig  -- "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/BigInteger.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/DataExchangeModel.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/DpiFix.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Extensions.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/AuthForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/AuthForm.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxEntryUserControl.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxEntryUserControl.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxFieldForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxFieldForm.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxGroupUserControl.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxGroupUserControl.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxURLForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxURLForm.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeyCreationSimpleForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeyCreationSimpleForm.designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/LocationManager.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/LocationManager.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/WelcomeForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/WelcomeForm.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPCClient.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPCExt.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPCServer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPCService.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/OptionsForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/OptionsForm.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeyChallengeResponse.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeyContainerClass.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Native.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Properties/AssemblyInfo.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Properties/Resources.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/RPCClientManagers.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/SRP.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/URLSummary.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Utils.cs"
/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/DataExchangeModel.cs(247,18): warning CS0659: `KeePassRPC.DataExchangeModel.EntryConfig' overrides Object.Equals(object) but does not override Object.GetHashCode()
/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeyCreationSimpleForm.cs(42,11): error CS0246: The type or namespace name `SecureEdit' could not be found. Are you missing an assembly reference?
/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeyCreationSimpleForm.cs(43,11): error CS0246: The type or namespace name `SecureEdit' could not be found. Are you missing an assembly reference?



==============================================================================
Compiler 'v3.5':

/nix/store/1k1n5j167cz1rqjnyhi63jg52bigxnj1-mono-5.4.1.6/bin/mcs /target:library /debug- /optimize+ /out:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.dll" /r:"System.dll" /r:"System.Configuration.dll" /r:"System.Configuration.Install.dll" /r:"System.Data.dll" /r:"System.Drawing.dll" /r:"System.Management.dll" /r:"System.Security.dll" /r:"System.Windows.Forms.dll" /r:"System.Xml.dll" /r:"/nix/store/mfvx22qhxlzm94jmrlm174cr1ii18riq-keepass-2.40/lib/dotnet/keepass/KeePass.exe" /r:"/home/user/.local/share/KeePass/PluginCache/m55ZrTiK9evjCyNUgeCg/DomainPublicSuffix.dll" /r:"/home/user/.local/share/KeePass/PluginCache/m55ZrTiK9evjCyNUgeCg/Fleck2.dll" /r:"/home/user/.local/share/KeePass/PluginCache/m55ZrTiK9evjCyNUgeCg/Jayrock.dll" /r:"/home/user/.local/share/KeePass/PluginCache/m55ZrTiK9evjCyNUgeCg/Jayrock.Json.dll" /r:"System.Core.dll" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.AuthForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.KeeFoxEntryUserControl.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.KeeFoxFieldForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.KeeFoxGroupUserControl.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.KeeFoxURLForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.KeyCreationSimpleForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.LocationManager.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.OptionsForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Forms.WelcomeForm.resources" /resource:"/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPC.Properties.Resources.resources" /noconfig  -- "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/BigInteger.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/DataExchangeModel.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/DpiFix.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Extensions.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/AuthForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/AuthForm.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxEntryUserControl.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxEntryUserControl.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxFieldForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxFieldForm.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxGroupUserControl.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxGroupUserControl.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxURLForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeeFoxURLForm.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeyCreationSimpleForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeyCreationSimpleForm.designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/LocationManager.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/LocationManager.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/WelcomeForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/WelcomeForm.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPCClient.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPCExt.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPCServer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeePassRPCService.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/OptionsForm.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/OptionsForm.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeyChallengeResponse.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/KeyContainerClass.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Native.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Properties/AssemblyInfo.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Properties/Resources.Designer.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/RPCClientManagers.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/SRP.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/URLSummary.cs" "/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Utils.cs"
/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/DataExchangeModel.cs(247,18): warning CS0659: `KeePassRPC.DataExchangeModel.EntryConfig' overrides Object.Equals(object) but does not override Object.GetHashCode()
/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeyCreationSimpleForm.cs(42,11): error CS0246: The type or namespace name `SecureEdit' could not be found. Are you missing an assembly reference?
/run/user/1000/KeePass/8AEF8A102A07E6469667CD4D99422BAE/Forms/KeyCreationSimpleForm.cs(43,11): error CS0246: The type or namespace name `SecureEdit' could not be found. Are you missing an assembly reference?

```

I also get a popup saying `Operation is not valid due to the current state of the object. Followed by a description of the KeePass object`

I've been trying to debug this for a while but couldn't find much. Hopefully It's just a library missing I'm not aware of.

Thank you for taking the time to read this!

**Comment by dlech** [comment]
The error is about missing `SecureEdit` which should be fixed in 1.8.0. Perhaps try clearing your plugin cache in KeePass.

**Comment by dlech** [comment]
And make sure you don't have two versions of KeePassRPC installed at the same time.

**Comment by M-Gregoire** [comment]
Thank you for your quick answer. 
I deleted the cache from "Tools > Plugins > Clear" in KeePass and checked I only I one version of KeePassRPC installed but the problem is still the same.

**Comment by M-Gregoire** [comment]
Thank you so much for your answer! I've been investigating cache issues as you explained my specific bug was fixed in 1.8.0.

I finally found that the `plgx` of keepass-rpc was kept in cache as I didn't update the hash in the nixpkgs, even though It was named `keepassrpc-1.8.0`.
After removing it and reinstalling it, It works perfectly!

This is a really life saver to finally have Keefox working!
